export const FETCH_LISTINGS_REQUEST = 'FETCH_LISTINGS_REQUEST';
export const FETCH_LISTINGS_SUCCESS = 'FETCH_LISTINGS_SUCCESS';
export const FETCH_LISTINGS_FAIL = 'FETCH_LISTINGS_FAIL';

export const CREATE_LISTING_REQUEST = 'CREATE_LISTING_REQUEST';
export const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS';
export const CREATE_LISTING_FAIL = 'CREATE_LISTING_FAIL';

export const UPDATE_LISTING_REQUEST = 'UPDATE_LISTING_REQUEST';
export const UPDATE_LISTING_SUCCESS = 'UPDATE_LISTING_SUCCESS';
export const UPDATE_LISTING_FAIL = 'UPDATE_LISTING_FAIL';

export const DELETE_LISTING_REQUEST = 'DELETE_LISTING_REQUEST';
export const DELETE_LISTING_SUCCESS = 'DELETE_LISTING_SUCCESS';
export const DELETE_LISTING_FAIL = 'DELETE_LISTING_FAIL';